cmake_minimum_required(VERSION 3.10)
project(tinyshell)
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
add_executable(tinyshell main.cpp commandParser.cpp builtins.cpp path.cpp file_manager.cpp logger.cpp ctrl_c_handler.cpp history.cpp process_manager.cpp process_executor.cpp environment.cpp)